### ISSUE TITLE
Filter out how to trigger the action.

### ISSUE THREAD

**Issue by olivierodo** [olivierodo/star-thankyou-action#9]
This action is mostly used to engage early adopter and hopefully get feedback from them.
That why some part of this action might not be relevant if the repository already reach a nice amount of stars.
So lets try to add some limit in the template such as:

```yaml
name: Thank you for the star

on:
  watch:
    types: [started]
jobs:
  thanks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Engage your supporters
      uses: atalent-labs/star-engagement-action@0.0.1
      with:
        limit: 500 # where 500 is the limit of activation for this action
```
